config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts, except: :inde
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts =  Post.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OurBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/_post.html.haml
.content
  .content__left
    .content__left--image
  .content__right
    .content__right__top
      = link_to post.title, post_path(post.id),class: "content__right__top--title"
    .content__right__bottom
      .content__right__bottom--userName
        = link_to post.user.nickname, user_path(post.user), class: "content__right__bottom--userName--btn"
      .content__right__bottom--date
        = post.created_at

app/views/posts/edit.html.haml
.content__title
  投稿の編集
= form_with model: @post, class: :form, local: true do |form|
  = form.text_field :title, placeholder: :タイトル, class: :form__title
  = form.text_area :content, placeholder: :ブログ本文, class: :form__text
  = form.submit '投稿する', class: :form__btn

app/views/posts/index.html.haml
.header
  .header__title
    =image_tag "logo.png",class:"header__title-image"
    %input{:type => "text",class:"header__title-text"}
    %input{:type => "submit"}
  .header__list
    %ul.header__list-left
      %li カテゴリー
      %li ブランド
    %ul.header__list-right
      %li ログイン
      %li 新規会員登録
.headline
  =image_tag "bg-mainVisual-pict_pc.jpg"
  .headline__title  
    人生を変えるフリマアプリ  
  .headline__text 
    FURIMAはだれでも簡単に出品・購入できるフリマアプリです
  .headline__link
    = link_to "App Store"
    = link_to "Google Play"
.reason
  .reason__title
    %h2 FURIMAが選ばれる3つの理由
  .reason__text
    %image_tag
    %image_tag
    %h3 3分ですぐ出品
    %p スマホで入力するだけで簡単に出品できる！
    %image_tag
    %image_tag 
    %h3 シンプルで使いやすい
    %p めんどくさい入力は必要なく、検索も購入もスムーズ！
    %image_tag
    %image_tag
    %h3 手数料 業界最安
    %p 最大3%でお得に出品&購入！
.grade
  .grade__title
    %h3 会員数日本一位
  .grade__text
    %p
      %br FURIMAは、フリマアプリで最も人気。
      %br 出品・購入回数も業界最多です！
      %br ほしかったあの商品に出会えるかもしれません。
    = link_to "App Store"
    = link_to "Google Play"
.feature
  .feature__title
    %h2 FURIMAの特徴
  .feature__text
    %image_tag
    %h3 簡単に売り買いできる
    %p スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
    %h3 売上金は即日振り込みに対応
    %p 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
    %h3 様々な支払いに対応
    %p お支払いは、クレジットカードだけではなく、ポイントや売上金など多彩な方法があります。
.category
  .category__title
    ピックアップカテゴリー
    %h3 新規投稿商品
  .category__text
    %image_tag
    %p product3
    %p 30000円
    %p （税込）
    %p ★
    %p 0
    %image_tag
    %p product2
    %p 20000円
    %p （税込）
    %p ★
    %p 0
    %image_tag
    %p product3
    %p 30000円
    %p （税込）
    %p ★
    %p 0
.publicity
  .publicity__title
    だれでもかんたん、人生を変えるフリマアプリ
  .publicity__text
    今すぐ無料ダウンロード！
  = link_to "App Store"
  = link_to "Google Play"
.footer
  .footer__text
    %h4 FURIMAについて
    =link_to"会社概要（運営会社）"
    =link_to"プライバシーポリシー"
    =link_to"FURIMA利用規約"
    =link_to"ポイントに関する特約"
  .footer__see
    %h4 FURIMAを見る
    =link_to"カテゴリー一覧"
    =link_to"ブランド一覧"
  .footer__help
    %h4 ヘルプ＆ガイド
    =link_to"FURIMAガイド"
    =link_to"FURIMAロゴ利用ガイドライン"
    =link_to"お知らせ"
  .footer__tilte
    %image_tag
    %p ©︎FURIMA
.icon
  .icon__title
    出品する
  .icon__image
    %image_tag

app/views/posts/new.html.haml
.content__title
  新規記事の作成
= form_with model: @post, class: :form, local: true do |form|
  = form.text_field :title, placeholder: :タイトル, class: :form__title
  = form.text_area :content, placeholder: :ブログ本文, class: :form__text
  = form.submit '投稿する', class: :form__btn

app/views/posts/show.html.haml
.postTitle
  = @post.title
.postDate
  = @post.created_at
.postAuthor
- if user_signed_in? && current_user.id == @post.user_id
  .postManage
    = link_to "編集", edit_post_path(@post.id), class: "postManage__edit"
    = link_to "削除", post_path(@post.id), method: :delete, class: "postManage__delete"
.postText
  = simple_format @post.content

app/views/users/show.html.haml
.postTitle
  = @user.nickname
  さんの投稿一覧
- @posts.each do |post|
  = render partial: "posts/post", locals: { post: post }
.content
  .content__left
    .content__left--image
  .content__right
    .content__right__top
      = link_to post.title, post_path(post.id), class: "content__right__top--title"
    .content__right__bottom
      .content__right__bottom--userName
        = link_to post.user.nickname, user_path(post.user), class: "content__right__bottom--userName--btn"
      .content__right__bottom--date
        = post.created_at